### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Cyl18** [RealSilverMoon/BoxPlusPlus#5]
![image](https://github.com/RealSilverMoon/BoxPlusPlus/assets/14993992/dd230a58-1a86-454b-a1ac-84075fe33acd)
```log
[01:31:26] [Client thread/INFO]: [codechicken.nei.NEIClientUtils:reportErrorBuffered:460]: Error while rendering: 64x@21
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: net.minecraft.util.ReportedException: Rendering item
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:604)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:660)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6606)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 2
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at gtPlusPlus.core.item.chemistry.IonParticles.getIconFromDamageForRenderPass(IonParticles.java:163)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.item.Item.getIcon(Item.java:1004)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraftforge.client.MinecraftForgeClient.handler$zhb000$hodgepodge$beforeRenderItem(MinecraftForgeClient.java:529)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraftforge.client.MinecraftForgeClient.getItemRenderer(MinecraftForgeClient.java)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:155)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:563)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:660)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:99)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1455)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:6606)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.lang.reflect.Method.invoke(Method.java:568)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at java.lang.reflect.Method.invoke(Method.java:568)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[01:31:26] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:763]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

![image](https://github.com/RealSilverMoon/BoxPlusPlus/assets/14993992/60b9ed33-1bd0-4e7a-b36d-7e6bcce780c7)

i have optifine and neodymium installed
GTNH 2.4.1 GraalVM EE(Java17)

**Comment by luomolhx** [comment]
这个问题是因为这个配方需要的GTPP的物品新版本被移除了
所以找不到了

**Comment by Cyl18** [comment]
好吧 看起来是不兼容2.4.1了 我更到2.5.0吧

**Comment by luomolhx** [comment]
> 好吧 看起来是不兼容2.4.1了 我更到2.5.0吧

看readme写的对应版本就行了

**Comment by Cyl18** [comment]
> > 好吧 看起来是不兼容2.4.1了 我更到2.5.0吧
> 
> 看readme写的对应版本就行了

我用1.4.x最新版都不行
